version: '3.7'

services:

  postgresql:
    container_name: pg_example
    image: postgres:12.15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      TZ: Asia/Tokyo
